bel = float(input("Введите массу белков: "))
zhir = float(input("Введите массу жиров: "))
ugl = float(input("Введите массу углеводов: "))
kkal = (bel*4)+(zhir*9)+(ugl*4)
print(f"Калорийность продукта составляет: {kkal} ккал")